---
title: "moco-behavior-report"
author: "Rick O. Gilmore"
date: "`r Sys.Date()`"
output: 
  html_document:
    keep_md: true
    self_contained: true
  ioslides_presentation:
    incremental: false
    widescreen: true
params:
  group: child
  dpi: 72
  plot_dev: png
  plot_titles: FALSE
---

```{r setup, include=FALSE}
path2figs <- paste('img', params$group, "", sep="/")
knitr::opts_chunk$set(dpi=params$dpi, dev=params$plot_dev, fig.path=path2figs, fig.width = 8.5, echo = FALSE, include = FALSE, warning = FALSE)
```

```{r initialize}
# load libraries
require(nlme)
require(dplyr)
require(ggplot2)
require(knitr)

# Source functions
fn.list <- list("analyses/plot.p.corr.R", 
                "analyses/plot.rt.R",
                "analyses/plot.p.corr.by.age.yrs.R")

# load and normalize data
if (params$group == "adult"){
  source("analyses/normalize.adult.data.R")
} else if (params$group == "child"){
  source("analyses/normalize.child.data.R")
} else {
  warning("Group unspecified. Using 'child' default.")
  source("analyses/normalize.child.data.R")
}

lapply(fn.list, source, echo = FALSE, print.eval = FALSE)
```

## Summary of participant ages, gender: `r params$group` group

```{r age-gender, echo=FALSE, include=TRUE}
# Summary table of age/gender dist
df.bysub.bycond %>% 
  group_by(Gender, AgeYrs, SubID) %>% 
  summarize(num = n()) -> df.gender.age
kable(xtabs(formula = ~ AgeYrs + Gender, data = df.gender.age))
```

## Plot of *p*(corr): `r params$group` group

```{r p.corr.plot, include=TRUE}
# Plot p(corr)
p1 <- plot.p.corr(df.bysub.bycond)
p1
```

## Plot of reaction time: `r params$group' group

```{r rt.plot, include=TRUE}
# Plot RTs
p2 <- plot.rt(df.bysub.bycond)
p2
```

## Plot of *p*(corr) by age in years: `r params$group` group

```{r p.corr.by.age, include=TRUE}
# Plot p(corr) by age
p3 <- plot.p.corr.by.age.yrs(df.bysub.bycond)
p3
```

## Linear mixed effects modeling of *p*(corr): `r params$group` group

```{r anova.p.corr, include=TRUE}
# Simple mixed linear modeling
lme.p.corr <- lme( Pct.Corr ~ Coh*PatternType*Speed, 
                   random = ~ 1 | SubID, 
                   data=df.bysub.bycond )
kable(anova(lme.p.corr))
```

## Evaluate Coherence x Speed interaction

```{r coh.by.spd.stats}
# Evaluate Speed by Coherence interaction
spd.by.coh <- df.bysub.bycond %>%
  group_by(Speed, Coh) %>%
  summarize(Pct.Corr.mean = mean(Pct.Corr, na.rm=TRUE),
            Pct.Corr.sem = sd(Pct.Corr, na.rm=TRUE)/sqrt( n() ))

limits = aes( ymax = Pct.Corr.mean + Pct.Corr.sem , ymin = Pct.Corr.mean - Pct.Corr.sem )

  theme.moco.plot <- theme(plot.title = element_text(size=18, face="bold"),
                           axis.title.x = element_text(size=18),
                           axis.title.y = element_text(size=18),
                           strip.text = element_text(size=16),
                           axis.text = element_text(size=12)
  )

p4 <- 
  ggplot( data=spd.by.coh, aes(x=Coh, y=Pct.Corr.mean) ) +
  facet_grid( facets = ~ Speed ) +
  geom_line() +
  geom_pointrange( limits ) +
  xlim(0,1) +
  ylim(.5, 1) +
  ylab("p(corr)") +
  xlab("p(coherence)") +
  theme(plot.title = element_text(size=18, face="bold"),
                           axis.title.x = element_text(size=18),
                           axis.title.y = element_text(size=18),
                           strip.text = element_text(size=16),
                           axis.text = element_text(size=14)
  )
```

```{r p.corr.by.spd.plot, include=TRUE}
p4
```

## Evaluate Coherence x Pattern interaction

```{r coh.by.pattern.stats}
# Evaluate PatternType x Coherence interaction
patt.by.coh <- df.bysub.bycond %>%
  group_by(PatternType, Coh) %>%
  summarize(Pct.Corr.mean = mean(Pct.Corr, na.rm=TRUE),
            Pct.Corr.sem = sd(Pct.Corr, na.rm=TRUE)/sqrt( n() ))

p5 <- 
  ggplot( data=patt.by.coh, aes(x=Coh, y=Pct.Corr.mean) ) +
  facet_grid( facets = ~ PatternType ) +
  geom_line() +
  geom_pointrange( limits ) +
  xlim(0, 1) +
  ylim(.5, 1) +
  ylab("p(corr)") +
  xlab("p(coherence)") +
  theme(plot.title = element_text(size=18, face="bold"),
                           axis.title.x = element_text(size=18),
                           axis.title.y = element_text(size=18),
                           strip.text = element_text(size=16),
                           axis.text = element_text(size=12)
  )
```

```{r coh.by.pattern.plot, include = TRUE}
p5
```
